# Generated by Django 4.2.5 on 2023-10-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_category_image_alter_productimage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imagesfour',
            field=models.ImageField(null=True, upload_to='product-images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='imagesone',
            field=models.ImageField(null=True, upload_to='product-images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='imagesthree',
            field=models.ImageField(null=True, upload_to='product-images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='imagestwo',
            field=models.ImageField(null=True, upload_to='product-images/'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
