# Generated by Django 4.2.5 on 2023-10-23 05:13

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_imagesfour_product_imagesone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttranslation',
            name='Specifications',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='this is the product', null=True),
        ),
    ]
