# Generated by Django 4.2.5 on 2023-10-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_review_product_alter_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttranslation',
            name='product_status',
            field=models.CharField(choices=[('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='in_review', max_length=10),
        ),
    ]
