# Generated by Django 4.2.5 on 2023-10-27 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_producttranslation_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewtranslation',
            name='subject',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(choices=[(1, '⭐☆☆☆☆'), (2, '⭐⭐☆☆☆'), (3, '⭐⭐⭐☆☆'), (4, '⭐⭐⭐⭐☆'), (5, '⭐⭐⭐⭐⭐')], default=None),
        ),
        migrations.AlterField(
            model_name='reviewtranslation',
            name='review',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
