# Generated by Django 4.2.5 on 2023-11-04 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_cart_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='qty',
        ),
        migrations.AddField(
            model_name='cart',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
