# Generated by Django 4.2.5 on 2023-11-04 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_remove_cart_product_cart_is_paid_cartitem_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='qty',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartitems', to='product.cart'),
        ),
    ]
