# Generated by Django 4.2.5 on 2023-11-07 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_wishlist_wishlistitem_delete_wishlist_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product'),
        ),
    ]
