# Generated by Django 4.2.5 on 2023-11-15 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_wishlistitem_product'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='addresstranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='addresstranslation',
            name='master',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='AddressTranslation',
        ),
    ]
