# Generated by Django 4.2.5 on 2023-11-21 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_alter_addresstranslation_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewtranslation',
            old_name='subject',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='reviewtranslation',
            name='review',
        ),
    ]
