"""
Django settings for ziabags project.

Generated by 'django-admin startproject' using Django 3.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os# i  did
from django.utils.translation import gettext_lazy as _
from dotenv import load_dotenv

load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = [
    os.environ.get("HOSTING_IP"),
    "127.0.0.1",
    "localhost",
    "www.ziabags.shop",
]





# Application definition

INSTALLED_APPS = [
    "unfold",  # before django.contrib.admin
    "unfold.contrib.filters",  # optional, if special filters are needed
    # ".forms",  # optional, if special form elements are needed
    "unfold.contrib.import_export",  # optional, if django-import-export package is used
    "django.contrib.admin",
  
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    # i did
    'users',
    'shoppingcart',
    'tailwind',
    'theme',
    'product',
    # 'debug_toolbar',
    'rosetta',
    'parler',
    'ckeditor',# third party
    # 'django_celery_results',
   
   

    
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'debug_toolbar.middleware.DebugToolbarMiddleware',# for djdt
    # 'users.middleware.PreventAdminMiddleware',  # Adjust the path based on your project structure

    # for translate
]

ROOT_URLCONF = 'ziabags.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
                'users.context_processors.cart_item_count',
                'users.context_processors.wishlist_item_count',
                'shoppingcart.context_processors.custom_admin_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'ziabags.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'ziabags',
#         'USER':'postgres',
#         'PASSWORD':'test123',
#         'HOST':'127.0.0.1',
#         'PORT':'5432',
#     }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'ziabags',
#         'USER': 'myprojectuser',
#         'PASSWORD': 'password',
#         'HOST': 'localhost',
#         'PORT': '',
#     }
# }

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("DB_NAME"),
        "USER": os.environ.get("DB_USER"),
        "PASSWORD": os.environ.get("DB_PASSWORD"),
        "HOST": os.environ.get("DB_HOST"),
        "PORT": os.environ.get("DB_PORT"),
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



LANGUAGE_CODE = 'en'

LANGUAGES=[
    ('en',_('English')),
    ('fa',_('Persian'))
]
PARLER_LANGUAGES={
    None:(
        {'code':'en'},
        {'code':'fa'},
    ),
    'default':{
        'fallbacks':['en'],
        'hide_untranslated':False,
    }
}
PARLER_DEFAULT_LANGUAGE_CODE = 'en'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True# localization

USE_TZ = True





# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/


 

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale/'),
]


STATIC_URL = '/assets/'
STATICFILES_DIRS=(os.path.join(BASE_DIR,'static'),) # i did
STATIC_ROOT=os.path.join(BASE_DIR,"assets") # i did tfytydr

MEDIA_URL="/media/"# i did
MEDIA_ROOT=os.path.join(BASE_DIR,"media")# i did

AUTH_USER_MODEL="users.UserProfile"# i did

TAILWIND_APP_NAME='theme'# i did

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


EMAIL_BACKEND='django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST='smtp.gmail.com'
EMAIL_USE_TLS=True
EMAIL_PORT=587
EMAIL_HOST_USER='ziabags1@gmail.com'
EMAIL_HOST_PASSWORD='ngizahhbycxjomrh'
DEFAULT_FROM_EMAIL='ziabags1@gmail.com'


CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    }
}

INTERNAL_IPS = [ 
    '127.0.0.1',  
]
CKEDITOR_UPLOAD_PATH ='uploads/'# foe ckeditor 


CKEDITOR_CONFIGS = {
    'default':{
        'skin':'moono',
        'codesnippet_theme':'monokai',
        'toolbar':'all',
        'extraplugins':','.join(
            [
                'codesnippet',
                'widget',
                'dialog'
            ]
        ),
    }
     
}

RAZORPAY_API_KEY = 'rzp_test_eZaik2w4bwkaAO'
RAZORPAY_API_SECRET = 'l006wj979Vdni9onzTQ4MKQj'


#celery configuration

# CELERY_BROKER_URL = 'redis://127.0.0.1:6379'
# CELERY_ACCEPT_CONTENT = {'application/json'}
# CELERY_RESULT_SERIALIZER = 'json'
# CELERY_TASK_SERIALIZER = 'json'
# CELERY_TIMEZONE = 'Europe/Paris'
# CELERY_RESULT_BACKEND = 'django-db'

