# Generated by Django 4.2.5 on 2023-11-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0003_cart_cartitem_remove_order_items_remove_order_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='product_covrer_images/'),
        ),
    ]
