# Generated by Django 4.2.5 on 2023-11-13 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0005_order_cartitem_product_orderitem_order_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='price',
        ),
    ]
