# Generated by Django 4.2.5 on 2023-11-13 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0006_remove_cartitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='title',
        ),
    ]
