# Generated by Django 4.2.5 on 2023-11-20 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0011_order_created_at_order_payment_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
