# Generated by Django 4.2.5 on 2023-12-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0014_remove_order_status_alter_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='line_total',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
