# Generated by Django 4.2.5 on 2023-12-05 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0015_remove_orderitem_line_total_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
