# Generated by Django 4.2.5 on 2023-12-06 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0017_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
